import type {
  Incident,
  PullRequestRec,
  Session,
  TimelineEntry,
} from '@oncall/shared';
import type { OncallDb } from '../db/index.js';
import { buildTimeline } from '../incidents/detail.js';

/**
 * Postmortem draft generator (SPEC §7.4, FR-18). Renders a markdown incident
 * report from the persisted incident + investigation session + PR + timeline.
 * `POST /incidents/:id/postmortem` generates + stores it on `incidents.postmortem`;
 * `GET` returns the stored draft.
 */

function tsLine(entry: TimelineEntry): string {
  return `- \`${new Date(entry.ts).toISOString()}\` — **${entry.kind}**: ${entry.label}`;
}

/** Build the markdown postmortem for an incident (pure). */
export function renderPostmortem(
  incident: Incident,
  session: Session | null,
  pr: PullRequestRec | null,
  timeline: TimelineEntry[],
): string {
  const rootCause = session?.root_cause ?? incident.root_cause ?? 'Not determined.';
  const confidence = session?.confidence ?? incident.confidence;
  const openedIso = new Date(incident.opened_at).toISOString();
  const resolvedIso =
    incident.resolved_at !== null ? new Date(incident.resolved_at).toISOString() : '—';

  const md: string[] = [];
  md.push(`# Postmortem — ${incident.title}`);
  md.push('');
  md.push('## Summary');
  md.push(
    `Incident \`${incident.id}\` on **${incident.service}** was detected by the ` +
      `\`${incident.detector}\` detector (observed ${incident.observed_value}, threshold ` +
      `${incident.threshold_value}). Status: **${incident.status}**.`,
  );
  md.push('');
  md.push('## Impact');
  md.push(`- Service: ${incident.service}`);
  md.push(`- Severity: ${incident.severity}`);
  md.push(`- Opened: ${openedIso}`);
  md.push(`- Resolved: ${resolvedIso}`);
  md.push('');
  md.push('## Root Cause');
  md.push(rootCause);
  if (typeof confidence === 'number') {
    md.push('');
    md.push(`_Agent confidence: ${(confidence * 100).toFixed(0)}%._`);
  }
  if (incident.suspect_deploy_sha) {
    md.push('');
    md.push(`Correlated deploy: \`${incident.suspect_deploy_sha}\`.`);
  }
  md.push('');
  md.push('## Timeline');
  if (timeline.length === 0) {
    md.push('_No timeline events recorded._');
  } else {
    for (const e of timeline) md.push(tsLine(e));
  }
  md.push('');
  md.push('## Resolution');
  if (pr) {
    md.push(
      `A ${pr.kind} fix was proposed as [PR #${pr.github_pr_number}](${pr.url}) ` +
        `(state: ${pr.state}, verification: ${pr.verification_status}).`,
    );
  } else if (incident.status === 'escalated') {
    md.push('Escalated to a human operator; no automated fix was opened.');
  } else {
    md.push('No pull request was associated with this incident.');
  }
  md.push('');
  md.push('## Action Items');
  md.push('- [ ] Review the proposed fix and confirm the root cause.');
  md.push('- [ ] Add a regression test covering this failure mode.');
  md.push('- [ ] Confirm alerting thresholds fired within the expected window.');
  md.push('');
  md.push('---');
  md.push('_Generated by OnCall AI — draft for human review._');
  md.push('');

  return md.join('\n');
}

/**
 * Generate the postmortem for an incident and persist it to `incidents.postmortem`.
 * Returns `null` when the incident does not exist.
 */
export function generateAndStorePostmortem(
  db: OncallDb,
  incidentId: string,
  customerId?: string,
): string | null {
  const incident = db.dao.incidents.getById(incidentId);
  if (!incident) return null;
  if (customerId !== undefined && incident.customer_id !== customerId) return null;

  const session = db.dao.sessions.latestForIncident(incidentId);
  const pr = db.dao.pullRequests.getByIncident(incidentId);
  const timeline = buildTimeline(incident, session ?? null, pr);
  const markdown = renderPostmortem(incident, session ?? null, pr, timeline);

  db.dao.incidents.update(incidentId, { postmortem: markdown });
  return markdown;
}
