import { mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, it, expect } from 'vitest';
import type { Incident, Step } from '@oncall/shared';
import {
  CachedEngine,
  cachedEngineFactory,
  createEngine,
  createPinnedGitHub,
  loadScenariosFromDir,
  resolveScenario,
  SCENARIO_NAMES,
  type AgentEngineConfig,
  type CachedScenario,
  type EngineSessionsDao,
  type EngineStepsDao,
  type PinnedGitHub,
  type ScenarioName,
} from '../src/index.js';
import {
  makeFakeDb,
  makeFakeGitHub,
  makeIncident,
  makeRecordingSink,
  PINNED,
  type FakeDb,
  type FakeGitHubSeed,
  type RecordingSink,
} from './helpers.js';

/* ── fixtures ──────────────────────────────────────────────────────────────── */

const BAD_SHA = 'bad0000000000000000000000000000000000000';
const PARENT_SHA = 'par0000000000000000000000000000000000000';
const SLOW_SHA = 'slo0000000000000000000000000000000000000';

function makeConfig(overrides: Partial<AgentEngineConfig['agent']> = {}): AgentEngineConfig {
  return {
    github: { ...PINNED },
    agent: {
      confidenceThreshold: 0.6,
      model: 'claude-sonnet-5',
      maxIterations: 10,
      costCapUsd: 0.25,
      mode: 'cached',
      useClaudeSubscription: true,
      cacheRealPr: true,
      ...overrides,
    },
  };
}

/** GitHub seed that makes create_fix_pr(revert BAD_SHA) succeed (mirrors engine.test). */
function githubSeed(): FakeGitHubSeed {
  return {
    refs: { 'heads/main': 'baseSha' },
    commits: {
      baseSha: { treeSha: 'baseTree' },
      [BAD_SHA]: {
        parents: [PARENT_SHA],
        message: 'remove cart null-guard',
        files: [
          {
            filename: 'src/routes/checkout.ts',
            status: 'modified',
            additions: 1,
            deletions: 1,
            patch: '@@\n-  const items = cart?.items ?? [];\n+  const items = cart.items;',
          },
        ],
      },
    },
    contents: {
      [`${PARENT_SHA}:src/routes/checkout.ts`]: 'const items = cart?.items ?? [];\n',
    },
    commitList: [{ sha: BAD_SHA, message: 'remove cart null-guard' }],
    prNumber: 7,
    prId: 700,
  };
}

/** A recorded bad_deploy scenario (the demo primary) — a clean propose_fix trace. */
function badDeployScenario(overrides: Partial<CachedScenario> = {}): CachedScenario {
  return {
    scenario: 'bad_deploy',
    recorded_at: 1_752_000_000_000,
    model: 'claude-sonnet-5',
    fingerprints: ['fp-bad-deploy'],
    match: {
      detector: 'error_rate',
      suspect_deploy_sha: BAD_SHA,
      keywords: ['null', 'undefined', 'cannot read'],
    },
    outcome: {
      status: 'completed',
      decision: 'propose_fix',
      root_cause: 'Null deref introduced by the bad deploy on checkout-api.',
      confidence: 0.92,
      iterations: 5,
      cost_usd: 0,
    },
    steps: [
      { type: 'thought', content: 'Confirming the error-rate breach with metrics.' },
      { type: 'tool_call', tool_name: 'get_metrics', tool_input: { service: 'checkout-api' } },
      {
        type: 'tool_result',
        tool_name: 'get_metrics',
        tool_output: { service: 'checkout-api', current: { error_rate: 0.85 } },
      },
      { type: 'tool_call', tool_name: 'get_recent_deploys', tool_input: { limit: 5 } },
      {
        type: 'tool_result',
        tool_name: 'get_recent_deploys',
        tool_output: { deploys: [{ sha: BAD_SHA, is_current: true }] },
      },
      { type: 'tool_call', tool_name: 'get_deploy_diff', tool_input: { sha: BAD_SHA } },
      {
        type: 'tool_result',
        tool_name: 'get_deploy_diff',
        tool_output: { files: [{ path: 'src/routes/checkout.ts', status: 'modified' }] },
      },
      {
        type: 'tool_call',
        tool_name: 'create_fix_pr',
        tool_input: {
          kind: 'revert',
          confidence: 0.92,
          root_cause: 'Null deref introduced by the bad deploy on checkout-api.',
          title: 'Revert "remove cart null-guard"',
          body: '## Root Cause\nNull deref.\n\n_Generated by OnCall AI._',
          revert_sha: BAD_SHA,
        },
      },
      {
        type: 'tool_result',
        tool_name: 'create_fix_pr',
        tool_output: {
          pr_number: 99,
          url: 'https://github.com/DIVIJ08070/oncall-ai-victim/pull/99',
          branch: 'oncall-ai/fix-rec-abc123',
          head_sha: 'recordedheadsha',
          base: 'main',
        },
      },
      {
        type: 'conclusion',
        tool_name: 'submit_findings',
        tool_input: {
          root_cause: 'Null deref introduced by the bad deploy on checkout-api.',
          evidence: [{ type: 'tool', tool: 'get_deploy_diff', ref: BAD_SHA }],
          confidence: 0.92,
          decision: 'propose_fix',
        },
        content: 'Null deref introduced by the bad deploy on checkout-api.',
      },
    ],
    ...overrides,
  };
}

/** A recorded escalate scenario (no create_fix_pr, decision=escalate). */
function escalateScenario(): CachedScenario {
  return {
    scenario: 'config_error',
    recorded_at: 1_752_000_000_000,
    model: 'claude-sonnet-5',
    fingerprints: ['fp-config'],
    match: { detector: 'error_rate', keywords: ['config', 'pricing'] },
    outcome: {
      status: 'escalated',
      decision: 'escalate',
      root_cause: 'Inconclusive — multiple candidate config changes.',
      confidence: 0.4,
      iterations: 3,
      cost_usd: 0,
    },
    steps: [
      { type: 'thought', content: 'Metrics are noisy; I cannot isolate a single change.' },
      { type: 'tool_call', tool_name: 'get_recent_deploys', tool_input: { limit: 5 } },
      { type: 'tool_result', tool_name: 'get_recent_deploys', tool_output: { deploys: [] } },
      {
        type: 'conclusion',
        tool_name: 'submit_findings',
        tool_input: {
          root_cause: 'Inconclusive — multiple candidate config changes.',
          evidence: [],
          confidence: 0.4,
          decision: 'escalate',
        },
        content: 'Inconclusive — multiple candidate config changes.',
      },
    ],
  };
}

/* ── test doubles ──────────────────────────────────────────────────────────── */

interface FakeSessions extends EngineSessionsDao {
  created: { id: string; incident_id: string; mode: string; model: string }[];
  finished: { id: string; status: string; decision?: unknown; root_cause?: unknown }[];
}
function makeFakeSessions(): FakeSessions {
  const created: FakeSessions['created'] = [];
  const finished: FakeSessions['finished'] = [];
  return {
    created,
    finished,
    create(input) {
      const id = `ses_${created.length + 1}`;
      created.push({ id, incident_id: input.incident_id, mode: input.mode, model: input.model });
      return { id };
    },
    finish(id, fields) {
      finished.push({ id, ...fields });
      return { id, ...fields };
    },
  };
}

interface FakeSteps extends EngineStepsDao {
  appended: {
    seq: number;
    type: string;
    tool_name?: string | null;
    tool_input?: unknown;
    tool_output?: unknown;
    content?: string | null;
  }[];
}
function makeFakeSteps(): FakeSteps {
  const appended: FakeSteps['appended'] = [];
  return {
    appended,
    append(input) {
      const seq = appended.length;
      appended.push({ seq, ...input });
      return { seq };
    },
  };
}

/** A pinned GitHub whose write path always fails (simulates Octokit offline). */
function failingOctokit(): PinnedGitHub {
  const offline = async (): Promise<never> => {
    throw new Error('Octokit: network is unreachable');
  };
  return {
    owner: PINNED.owner,
    repo: PINNED.repo,
    defaultBranch: PINNED.defaultBranch,
    listCommits: offline,
    getCommitDiff: offline,
    compare: offline,
    getFile: offline,
    openRevertPr: offline,
    openPatchPr: offline,
  };
}

interface Harness {
  engine: CachedEngine;
  incident: Incident;
  db: FakeDb;
  sessions: FakeSessions;
  steps: FakeSteps;
  sink: RecordingSink & { steps: Step[] };
}

function makeHarness(opts: {
  scenarios?: Partial<Record<ScenarioName, CachedScenario>>;
  config?: AgentEngineConfig;
  incident?: Partial<Incident>;
  octokit?: PinnedGitHub;
  seed?: FakeGitHubSeed;
  realPr?: boolean;
  forceScenario?: ScenarioName;
} = {}): Harness {
  const config = opts.config ?? makeConfig();
  const incident = makeIncident({ suspect_deploy_sha: BAD_SHA, ...opts.incident });
  const db = makeFakeDb({}, incident);
  const octokit =
    opts.octokit ?? createPinnedGitHub(makeFakeGitHub(opts.seed ?? githubSeed()).client, config.github);
  const sessions = makeFakeSessions();
  const steps = makeFakeSteps();

  const baseSink = makeRecordingSink();
  const emittedSteps: Step[] = [];
  const sink = Object.assign(baseSink, {
    steps: emittedSteps,
    step: (s: Step) => void emittedSteps.push(s),
  });

  const engine = new CachedEngine({
    db,
    octokit,
    config,
    sessions,
    steps,
    scenarios: opts.scenarios ?? { bad_deploy: badDeployScenario() },
    sleep: async () => {}, // no-op → tests run instantly, deterministically
    random: () => 0,
    realPr: opts.realPr,
    forceScenario: opts.forceScenario,
    now: () => 1_752_000_000_000,
  });

  return { engine, incident, db, sessions, steps, sink };
}

/* ── 1. deterministic replay to the same StepSink ─────────────────────────── */

describe('CachedEngine — deterministic replay (NFR-06 feed parity)', () => {
  const EXPECTED: Array<[string, string | null]> = [
    ['thought', null],
    ['tool_call', 'get_metrics'],
    ['tool_result', 'get_metrics'],
    ['tool_call', 'get_recent_deploys'],
    ['tool_result', 'get_recent_deploys'],
    ['tool_call', 'get_deploy_diff'],
    ['tool_result', 'get_deploy_diff'],
    ['tool_call', 'create_fix_pr'],
    ['tool_result', 'create_fix_pr'],
    ['conclusion', 'submit_findings'],
  ];

  it('emits the recorded step sequence to the sink, seq monotonic, persisted == emitted', async () => {
    const h = makeHarness({ realPr: true });
    const result = await h.engine.investigate(h.incident, h.sink);

    // Same step type/tool sequence as recorded (recorded create_fix_pr tool_result
    // is replaced in place by the live one — one per position).
    expect(h.sink.steps.map((s) => [s.type, s.tool_name ?? null])).toEqual(EXPECTED);

    // seq 0..n monotonic; every persisted step was also emitted, in order.
    expect(h.sink.steps.map((s) => s.seq)).toEqual(h.steps.appended.map((s) => s.seq));
    for (let i = 0; i < h.sink.steps.length; i++) expect(h.sink.steps[i].seq).toBe(i);

    // mode = cached everywhere.
    expect(result.mode).toBe('cached');
    expect(h.sessions.created[0].mode).toBe('cached');
    expect(h.sessions.finished[0].status).toBe('completed');
  });

  it('is byte-for-byte stable across repeated runs', async () => {
    const seq = async (): Promise<string> => {
      const h = makeHarness({ realPr: false }); // canned → fully offline determinism
      await h.engine.investigate(h.incident, h.sink);
      return JSON.stringify(h.sink.steps.map((s) => [s.type, s.tool_name ?? null, s.seq]));
    };
    expect(await seq()).toBe(await seq());
  });

  it('surfaces conclusion once with the recorded decision/confidence', async () => {
    const h = makeHarness({ realPr: true });
    const result = await h.engine.investigate(h.incident, h.sink);
    expect(h.sink.conclusionCalls).toHaveLength(1);
    expect(h.sink.conclusionCalls[0].decision).toBe('propose_fix');
    expect(h.sink.conclusionCalls[0].confidence).toBe(0.92);
    expect(result.decision).toBe('propose_fix');
    expect(result.root_cause).toContain('Null deref');
    expect(result.iterations).toBe(5);
  });
});

/* ── 2. scenario selection by fingerprint / heuristics ────────────────────── */

describe('CachedEngine — scenario selection (fingerprint → scenario map)', () => {
  const catalogue = {
    bad_deploy: badDeployScenario(),
    slow_db: {
      ...badDeployScenario(),
      scenario: 'slow_db' as const,
      fingerprints: ['fp-slow'],
      match: { detector: 'latency', suspect_deploy_sha: SLOW_SHA, keywords: ['slow', 'latency'] },
    },
    config_error: escalateScenario(),
  };

  it('resolves by exact incident fingerprint', () => {
    expect(resolveScenario(makeIncident({ fingerprint: 'fp-bad-deploy' }), catalogue)).toBe(
      'bad_deploy',
    );
    expect(resolveScenario(makeIncident({ fingerprint: 'fp-slow' }), catalogue)).toBe('slow_db');
    expect(resolveScenario(makeIncident({ fingerprint: 'fp-config' }), catalogue)).toBe(
      'config_error',
    );
  });

  it('falls back to suspect_deploy_sha, then detector, then keywords', () => {
    // suspect SHA (fingerprint unknown)
    expect(
      resolveScenario(
        makeIncident({ fingerprint: 'nomatch', suspect_deploy_sha: SLOW_SHA }),
        catalogue,
      ),
    ).toBe('slow_db');
    // detector=latency → slow_db
    expect(
      resolveScenario(makeIncident({ fingerprint: 'nomatch', detector: 'latency' }), catalogue),
    ).toBe('slow_db');
    // keyword: config
    expect(
      resolveScenario(
        makeIncident({
          fingerprint: 'nomatch',
          detector: 'error_rate',
          title: 'Missing config PRICING_TABLE on pricing-api',
        }),
        catalogue,
      ),
    ).toBe('config_error');
    // keyword: null deref → bad_deploy
    expect(
      resolveScenario(
        makeIncident({
          fingerprint: 'nomatch',
          detector: 'error_rate',
          suspect_deploy_sha: null,
          title: "Cannot read properties of undefined (reading 'items')",
        }),
        catalogue,
      ),
    ).toBe('bad_deploy');
  });

  it('defaults to the primary scenario and returns null on an empty catalogue', () => {
    expect(
      resolveScenario(
        makeIncident({ fingerprint: 'nomatch', detector: 'error_rate', suspect_deploy_sha: null, title: 'totally unknown' }),
        catalogue,
      ),
    ).toBe('bad_deploy');
    expect(resolveScenario(makeIncident(), {})).toBeNull();
  });

  it('routes a latency incident through the slow_db replay end-to-end', async () => {
    const h = makeHarness({
      scenarios: catalogue,
      incident: { detector: 'latency', suspect_deploy_sha: SLOW_SHA, fingerprint: 'fp-slow' },
      realPr: false,
    });
    await h.engine.investigate(h.incident, h.sink);
    expect(h.sessions.created[0].model).toBe('claude-sonnet-5');
    // slow_db fixture is a propose_fix trace → a PR record surfaces.
    expect(h.sink.prCreatedCalls).toHaveLength(1);
  });
});

/* ── 3. CACHE_REAL_PR path opens a REAL PR ────────────────────────────────── */

describe('CachedEngine — real-PR fallback (§13, CACHE_REAL_PR=true)', () => {
  it('executes the real create_fix_pr tool and opens a genuine PR', async () => {
    const h = makeHarness({ realPr: true, seed: githubSeed() });
    const result = await h.engine.investigate(h.incident, h.sink);

    // The tool_result carries the REAL new PR (#7 from the seed), not the recorded #99.
    const prResult = h.sink.steps.find(
      (s) => s.type === 'tool_result' && s.tool_name === 'create_fix_pr',
    )!;
    expect((prResult.tool_output as { pr_number?: number }).pr_number).toBe(7);
    expect((prResult.tool_output as { cached?: boolean }).cached).toBeUndefined();

    // A real PR row was persisted + the incident linked fix_proposed (real tool side effects).
    expect(h.db.createdPrs).toHaveLength(1);
    expect(h.db.createdPrs[0].github_pr_number).toBe(7);
    expect(h.db.patches.some((p) => p.patch.status === 'fix_proposed')).toBe(true);

    // sink pr_created fired once with the real PR; result reflects it.
    expect(h.sink.prCreatedCalls).toHaveLength(1);
    expect(h.sink.prCreatedCalls[0].number).toBe(7);
    expect(result.pr_number).toBe(7);
    expect(result.status).toBe('completed');
    expect(result.decision).toBe('propose_fix');
  });
});

/* ── 4. Octokit-failure fallback → canned PR record ───────────────────────── */

describe('CachedEngine — Octokit-failure fallback → canned PR record (§13)', () => {
  it('falls back to the recorded canned PR when the real tool throws', async () => {
    const h = makeHarness({ realPr: true, octokit: failingOctokit() });
    const result = await h.engine.investigate(h.incident, h.sink);

    // Canned PR = the one captured at record time (#99), flagged cached.
    const prResult = h.sink.steps.find(
      (s) => s.type === 'tool_result' && s.tool_name === 'create_fix_pr',
    )!;
    expect((prResult.tool_output as { pr_number?: number }).pr_number).toBe(99);
    expect((prResult.tool_output as { cached?: boolean }).cached).toBe(true);

    // The demo still continues: a PR row is persisted + incident linked + pr_created fired.
    expect(h.db.createdPrs).toHaveLength(1);
    expect(h.db.createdPrs[0].github_pr_number).toBe(99);
    expect(h.db.patches.some((p) => p.patch.status === 'fix_proposed')).toBe(true);
    expect(h.sink.prCreatedCalls).toHaveLength(1);
    expect(h.sink.prCreatedCalls[0].number).toBe(99);

    // Session still completes as a proposed fix (feed parity holds).
    expect(result.status).toBe('completed');
    expect(result.decision).toBe('propose_fix');
    expect(result.pr_number).toBe(99);
  });

  it('with CACHE_REAL_PR disabled, always uses the canned record (no GitHub call)', async () => {
    // A working octokit is provided, but realPr=false → the tool is never invoked.
    const h = makeHarness({ realPr: false, seed: githubSeed() });
    const result = await h.engine.investigate(h.incident, h.sink);
    const prResult = h.sink.steps.find(
      (s) => s.type === 'tool_result' && s.tool_name === 'create_fix_pr',
    )!;
    expect((prResult.tool_output as { pr_number?: number }).pr_number).toBe(99); // canned, not 7
    expect((prResult.tool_output as { cached?: boolean }).cached).toBe(true);
    expect(result.pr_number).toBe(99);
  });
});

/* ── 5. escalation replay + empty-catalogue degradation ───────────────────── */

describe('CachedEngine — escalation + degradation', () => {
  it('replays an escalate scenario → escalated, no PR', async () => {
    const h = makeHarness({
      scenarios: { config_error: escalateScenario() },
      incident: { detector: 'error_rate', suspect_deploy_sha: null, title: 'config error on pricing' },
      realPr: true,
    });
    const result = await h.engine.investigate(h.incident, h.sink);

    expect(result.status).toBe('escalated');
    expect(result.decision).toBe('escalate');
    expect(result.pr_number).toBeNull();
    expect(h.db.createdPrs).toHaveLength(0);
    expect(h.sink.prCreatedCalls).toHaveLength(0);
    expect(h.db.patches.some((p) => p.patch.status === 'escalated')).toBe(true);
    expect(h.sink.conclusionCalls[0].decision).toBe('escalate');
  });

  it('escalates gracefully when no scenario is available (empty cache)', async () => {
    const h = makeHarness({ scenarios: {} });
    const result = await h.engine.investigate(h.incident, h.sink);
    expect(result.status).toBe('escalated');
    expect(result.decision).toBe('escalate');
    expect(h.sink.steps.some((s) => s.type === 'error')).toBe(true);
    expect(h.db.patches.some((p) => p.patch.status === 'escalated')).toBe(true);
  });
});

/* ── 6. factory + FS loader integration ───────────────────────────────────── */

describe('CachedEngine — factory + committed cache loader', () => {
  it('createEngine(mode=cached) with cachedEngineFactory returns a CachedEngine', () => {
    const config = makeConfig({ mode: 'cached' });
    const incident = makeIncident();
    const db = makeFakeDb({}, incident);
    const octokit = createPinnedGitHub(makeFakeGitHub().client, config.github);
    const engine = createEngine({
      db,
      octokit,
      config,
      sessions: makeFakeSessions(),
      steps: makeFakeSteps(),
      cachedEngineFactory,
    });
    expect(engine).toBeInstanceOf(CachedEngine);
  });

  it('loadScenariosFromDir reads valid <scenario>.json and skips junk', () => {
    const dir = mkdtempSync(join(tmpdir(), 'oncall-cache-'));
    writeFileSync(join(dir, 'bad_deploy.json'), JSON.stringify(badDeployScenario()));
    writeFileSync(join(dir, 'broken.json'), '{ not valid json');
    writeFileSync(join(dir, 'notes.txt'), 'ignore me');
    const loaded = loadScenariosFromDir(dir);
    expect(Object.keys(loaded)).toEqual(['bad_deploy']);
    expect(loaded.bad_deploy!.scenario).toBe('bad_deploy');
    // missing dir → empty (no throw).
    expect(loadScenariosFromDir(join(dir, 'does-not-exist'))).toEqual({});
  });

  it('the committed packages/agent/cache is valid (if present)', () => {
    const loaded = loadScenariosFromDir(new URL('../cache', import.meta.url).pathname);
    for (const [name, sc] of Object.entries(loaded)) {
      expect((SCENARIO_NAMES as readonly string[])).toContain(name);
      expect(sc!.scenario).toBe(name);
      expect(Array.isArray(sc!.steps)).toBe(true);
      expect(sc!.steps.length).toBeGreaterThan(0);
    }
    // bad_deploy is the demo primary — it must exist in the committed cache.
    expect(loaded.bad_deploy).toBeDefined();
  });
});
