import type pg from 'pg';
/** Bumped with every DDL change (was shared with the sqlite driver). */
const SCHEMA_VERSION = 2;
import { withTransaction } from './pool.js';

/**
 * Idempotent PostgreSQL schema migration — the full sqlite DDL (SPEC §8)
 * translated, plus the AI Incident PREVENTION tables (Phase 1). All 15 tables
 * + indexes, executed inside **one transaction**.
 *
 * Translation decisions (sqlite → postgres):
 *
 *  - `TEXT` → `TEXT` (ids stay prefixed-ULID strings; no identity change).
 *  - `INTEGER` → `BIGINT` everywhere: ms-epoch timestamps exceed int4 range,
 *    and one uniform integer type keeps the DDL predictable. `pool.ts`
 *    registers an int8 → JS-number parser so row shapes match sqlite exactly.
 *  - `REAL` → `DOUBLE PRECISION` (float8, natively parsed to JS number).
 *  - `INTEGER PRIMARY KEY AUTOINCREMENT` (metric_samples.id) →
 *    `BIGINT GENERATED BY DEFAULT AS IDENTITY` — BY DEFAULT (not ALWAYS) so
 *    tests/replay may still insert explicit ids; inserts use `RETURNING id`.
 *  - Booleans stay `0/1` integers (`deploys.is_current`) so the shared
 *    `boolToInt`/`intToBool` codecs work identically on both drivers.
 *  - The intentional **cyclic FK** (`incidents.pr_id → pull_requests.id` and
 *    `pull_requests.incident_id → incidents.id`): postgres, unlike sqlite,
 *    refuses an inline FK to a not-yet-created table, so `incidents` is
 *    created without it and the constraint is added afterwards via an
 *    idempotent `DO` block once `pull_requests` exists.
 *  - sqlite's `PRAGMA user_version` → a single-row `schema_version` table.
 */

const DDL = /* sql */ `
-- ── customers (services/customers) ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS customers (
  id              TEXT PRIMARY KEY,
  name            TEXT NOT NULL,
  ingest_api_key  TEXT NOT NULL UNIQUE,
  github_owner    TEXT,
  github_repo     TEXT,
  default_branch  TEXT NOT NULL DEFAULT 'main',
  created_at      BIGINT NOT NULL
);

-- ── users (OAuth, FR-15) ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS users (
  id              TEXT PRIMARY KEY,
  github_user_id  BIGINT NOT NULL UNIQUE,
  github_login    TEXT NOT NULL,
  avatar_url      TEXT,
  access_token    TEXT,
  customer_id     TEXT REFERENCES customers(id),
  created_at      BIGINT NOT NULL
);

-- ── services (health + silence heartbeat) ───────────────────────────────────
CREATE TABLE IF NOT EXISTS services (
  id              TEXT PRIMARY KEY,
  customer_id     TEXT NOT NULL REFERENCES customers(id),
  name            TEXT NOT NULL,
  first_event_at  BIGINT,
  last_event_at   BIGINT,
  UNIQUE(customer_id, name)
);

-- ── log_events (FR-03) ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS log_events (
  id               TEXT PRIMARY KEY,
  customer_id      TEXT NOT NULL REFERENCES customers(id),
  service          TEXT NOT NULL,
  timestamp        BIGINT NOT NULL,
  received_at      BIGINT NOT NULL,
  level            TEXT NOT NULL,
  message          TEXT NOT NULL,
  stack            TEXT,
  endpoint         TEXT,
  method           TEXT,
  status           BIGINT,
  latency_ms       BIGINT,
  fingerprint_sig  TEXT
);
CREATE INDEX IF NOT EXISTS idx_log_events_cust_svc_ts      ON log_events(customer_id, service, timestamp);
CREATE INDEX IF NOT EXISTS idx_log_events_cust_lvl_ts      ON log_events(customer_id, level, timestamp);
CREATE INDEX IF NOT EXISTS idx_log_events_cust_svc_lvl_ts  ON log_events(customer_id, service, level, timestamp);
CREATE INDEX IF NOT EXISTS idx_log_events_cust_ts          ON log_events(customer_id, timestamp);
CREATE INDEX IF NOT EXISTS idx_log_events_fingerprint      ON log_events(fingerprint_sig);

-- ── metric_samples (FR-04; written each detection tick) ─────────────────────
CREATE TABLE IF NOT EXISTS metric_samples (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id    TEXT NOT NULL REFERENCES customers(id),
  service        TEXT NOT NULL,
  bucket_ts      BIGINT NOT NULL,
  window_sec     BIGINT NOT NULL,
  request_count  BIGINT NOT NULL,
  error_count    BIGINT NOT NULL,
  error_rate     DOUBLE PRECISION NOT NULL,
  p50_ms         BIGINT NOT NULL,
  p95_ms         BIGINT NOT NULL,
  p99_ms         BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_metric_samples_cust_svc_bucket ON metric_samples(customer_id, service, bucket_ts);

-- ── incidents (FR-05 dedup + lifecycle) ─────────────────────────────────────
-- NOTE: the FK on pr_id is added below (cyclic with pull_requests).
CREATE TABLE IF NOT EXISTS incidents (
  id                  TEXT PRIMARY KEY,
  customer_id         TEXT NOT NULL REFERENCES customers(id),
  service             TEXT NOT NULL,
  detector            TEXT NOT NULL,
  fingerprint         TEXT NOT NULL,
  title               TEXT NOT NULL,
  status              TEXT NOT NULL,
  severity            TEXT NOT NULL,
  threshold_value     DOUBLE PRECISION NOT NULL,
  observed_value      DOUBLE PRECISION NOT NULL,
  first_error_at      BIGINT,
  detected_at         BIGINT NOT NULL,
  opened_at           BIGINT NOT NULL,
  root_cause          TEXT,
  confidence          DOUBLE PRECISION,
  pr_id               TEXT,
  suspect_deploy_sha  TEXT,
  resolved_at         BIGINT,
  postmortem          TEXT,
  updated_at          BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_incidents_cust_status ON incidents(customer_id, status);
CREATE INDEX IF NOT EXISTS idx_incidents_dedup       ON incidents(customer_id, service, fingerprint, status);

-- ── investigation_sessions (FR-06/08) ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS investigation_sessions (
  id             TEXT PRIMARY KEY,
  incident_id    TEXT NOT NULL REFERENCES incidents(id),
  status         TEXT NOT NULL,
  mode           TEXT NOT NULL,
  model          TEXT NOT NULL,
  started_at     BIGINT NOT NULL,
  completed_at   BIGINT,
  iterations     BIGINT NOT NULL,
  root_cause     TEXT,
  confidence     DOUBLE PRECISION,
  decision       TEXT,
  summary        TEXT,
  input_tokens   BIGINT NOT NULL,
  output_tokens  BIGINT NOT NULL,
  cost_usd       DOUBLE PRECISION NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_sessions_incident ON investigation_sessions(incident_id);

-- ── investigation_steps (NFR-06 transparency + live feed) ───────────────────
CREATE TABLE IF NOT EXISTS investigation_steps (
  id           TEXT PRIMARY KEY,
  session_id   TEXT NOT NULL REFERENCES investigation_sessions(id),
  seq          BIGINT NOT NULL,
  type         TEXT NOT NULL,
  tool_name    TEXT,
  tool_input   TEXT,
  tool_output  TEXT,
  content      TEXT,
  created_at   BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_steps_session_seq ON investigation_steps(session_id, seq);

-- ── deploys (correlation + recovery) ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS deploys (
  id            TEXT PRIMARY KEY,
  customer_id   TEXT NOT NULL REFERENCES customers(id),
  sha           TEXT NOT NULL,
  short_sha     TEXT NOT NULL,
  ref           TEXT NOT NULL,
  message       TEXT NOT NULL,
  author        TEXT NOT NULL,
  committed_at  BIGINT NOT NULL,
  deployed_at   BIGINT,
  is_current    BIGINT NOT NULL DEFAULT 0,
  source        TEXT NOT NULL,
  pr_id         TEXT,
  created_at    BIGINT NOT NULL,
  UNIQUE(customer_id, sha)
);
CREATE INDEX IF NOT EXISTS idx_deploys_cust_current   ON deploys(customer_id, is_current);
CREATE INDEX IF NOT EXISTS idx_deploys_cust_committed ON deploys(customer_id, committed_at);

-- ── pull_requests (FR-09/10/12) ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS pull_requests (
  id                       TEXT PRIMARY KEY,
  incident_id              TEXT NOT NULL REFERENCES incidents(id),
  customer_id              TEXT NOT NULL REFERENCES customers(id),
  github_pr_number         BIGINT NOT NULL,
  github_pr_id             BIGINT NOT NULL,
  branch                   TEXT NOT NULL,
  base_branch              TEXT NOT NULL,
  title                    TEXT NOT NULL,
  url                      TEXT NOT NULL,
  kind                     TEXT NOT NULL,
  state                    TEXT NOT NULL,
  diagnostic_report        TEXT NOT NULL,
  head_sha                 TEXT NOT NULL,
  created_at               BIGINT NOT NULL,
  merged_at                BIGINT,
  verification_status      TEXT NOT NULL,
  verification_comment_id  BIGINT
);
CREATE INDEX IF NOT EXISTS idx_pull_requests_incident   ON pull_requests(incident_id);
CREATE INDEX IF NOT EXISTS idx_pull_requests_cust_state ON pull_requests(customer_id, state);

-- Close the intentional FK cycle now that pull_requests exists (idempotent).
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk_incidents_pr_id'
  ) THEN
    ALTER TABLE incidents
      ADD CONSTRAINT fk_incidents_pr_id
      FOREIGN KEY (pr_id) REFERENCES pull_requests(id);
  END IF;
END
$$;

-- ── chat_messages (FR-16) ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS chat_messages (
  id           TEXT PRIMARY KEY,
  incident_id  TEXT REFERENCES incidents(id),
  role         TEXT NOT NULL,
  content      TEXT NOT NULL,
  evidence     TEXT,
  created_at   BIGINT NOT NULL
);
-- id is a monotonic-ULID tiebreaker so same-millisecond rows return in
-- insertion order (BUG-006); it also fully covers the DAO ORDER BY.
CREATE INDEX IF NOT EXISTS idx_chat_messages_incident_created ON chat_messages(incident_id, created_at, id);

-- ── notifications (FR-17 stub) ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS notifications (
  id           TEXT PRIMARY KEY,
  incident_id  TEXT NOT NULL REFERENCES incidents(id),
  channel      TEXT NOT NULL,
  status       TEXT NOT NULL,
  payload      TEXT NOT NULL,
  created_at   BIGINT NOT NULL
);

-- ── repo_learnings (per-repo self-learning feedback) ────────────────────────
CREATE TABLE IF NOT EXISTS repo_learnings (
  id             TEXT PRIMARY KEY,
  repo           TEXT NOT NULL,
  error_class    TEXT NOT NULL,
  root_cause     TEXT NOT NULL,
  fix_approach   TEXT,
  source         TEXT NOT NULL CHECK (source IN ('rating','merge','closed','review')),
  rating         BIGINT NOT NULL DEFAULT 0,
  note           TEXT,
  confirmations  BIGINT NOT NULL DEFAULT 1,
  pr_number      BIGINT,
  created_at     BIGINT NOT NULL,
  updated_at     BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_repo_learnings_repo ON repo_learnings(repo);

-- ── api_performance_samples (AI Incident PREVENTION Phase 1) ────────────────
-- One row per (service, endpoint) per rollup window: the derived performance
-- profile (percentiles, rates, RPS), a 0-100 performance_score, a 0-100
-- risk_score, and a human-readable trend prediction. Rebuilt/updated each
-- window via ON CONFLICT (service_name, endpoint, window_start).
CREATE TABLE IF NOT EXISTS api_performance_samples (
  id                 BIGSERIAL PRIMARY KEY,
  service_name       TEXT NOT NULL,
  endpoint           TEXT NOT NULL,
  method             TEXT NOT NULL,
  window_start       BIGINT NOT NULL,
  window_end         BIGINT NOT NULL,
  request_count      BIGINT NOT NULL,
  rps                DOUBLE PRECISION NOT NULL,
  p50_latency_ms     DOUBLE PRECISION NOT NULL,
  p95_latency_ms     DOUBLE PRECISION NOT NULL,
  p99_latency_ms     DOUBLE PRECISION NOT NULL,
  error_rate         DOUBLE PRECISION NOT NULL,
  timeout_rate       DOUBLE PRECISION NOT NULL,
  performance_score  DOUBLE PRECISION NOT NULL,
  risk_score         DOUBLE PRECISION NOT NULL,
  prediction         TEXT,
  UNIQUE(service_name, endpoint, window_start)
);
CREATE INDEX IF NOT EXISTS idx_api_perf_svc_ep_window
  ON api_performance_samples(service_name, endpoint, window_start DESC);

-- ── risk_states (AI Incident PREVENTION Phase 1) ────────────────────────────
-- Durable per-(service, endpoint) escalation state driven by successive
-- performance windows: current status, consecutive risk/healthy streaks, the
-- live risk score, and the serialized prediction detail. One row per endpoint
-- via ON CONFLICT (service_name, endpoint).
CREATE TABLE IF NOT EXISTS risk_states (
  id                           BIGSERIAL PRIMARY KEY,
  service_name                 TEXT NOT NULL,
  endpoint                     TEXT NOT NULL,
  status                       TEXT NOT NULL,
  first_detected_at            BIGINT,
  last_escalated_at            BIGINT,
  consecutive_risk_windows     BIGINT NOT NULL DEFAULT 0,
  consecutive_healthy_windows  BIGINT NOT NULL DEFAULT 0,
  current_risk_score           DOUBLE PRECISION,
  prediction_details           TEXT,
  updated_at                   BIGINT NOT NULL,
  UNIQUE(service_name, endpoint)
);

-- ── schema_version (sqlite PRAGMA user_version equivalent) ──────────────────
CREATE TABLE IF NOT EXISTS schema_version (
  id       INTEGER PRIMARY KEY CHECK (id = 1),
  version  BIGINT NOT NULL
);
`;

/** Error code for "relation does not exist" (never-migrated database). */
const UNDEFINED_TABLE = '42P01';

/**
 * Create every table + index if absent and record the schema version, all in
 * one transaction. Idempotent — running twice is a no-op. Returns the schema
 * version now recorded in `schema_version`.
 */
export async function migratePg(pool: pg.Pool): Promise<number> {
  await withTransaction(pool, async (client) => {
    await client.query(DDL);
    await client.query(
      `INSERT INTO schema_version (id, version) VALUES (1, $1)
       ON CONFLICT (id) DO UPDATE SET version = EXCLUDED.version`,
      [SCHEMA_VERSION],
    );
  });
  return SCHEMA_VERSION;
}

/** Read the recorded schema version (0 if never migrated). */
export async function schemaVersionPg(pool: pg.Pool): Promise<number> {
  try {
    const res = await pool.query<{ version: number }>(
      `SELECT version FROM schema_version WHERE id = 1`,
    );
    return res.rows[0]?.version ?? 0;
  } catch (err) {
    if ((err as { code?: string }).code === UNDEFINED_TABLE) return 0;
    throw err;
  }
}

/** List existing user tables (for tests / diagnostics). */
export async function existingTablesPg(pool: pg.Pool): Promise<string[]> {
  const res = await pool.query<{ tablename: string }>(
    `SELECT tablename FROM pg_tables WHERE schemaname = 'public' ORDER BY tablename`,
  );
  return res.rows.map((r) => r.tablename);
}
