import type pg from 'pg';
import type { MetricSample } from '@oncall/shared';
import type {
  CreateMetricSampleInput,
  MetricSamplesDao,
} from '../../dao/types.js';

/**
 * `metric_samples` DAO, postgres driver (FR-04). The only table with an
 * auto-assigned integer PK — the pg schema uses `GENERATED BY DEFAULT AS
 * IDENTITY` and `insert` reads the assigned id via `RETURNING id` (the pg
 * counterpart of sqlite's `lastInsertRowid`).
 */
export class PgMetricSamplesDao implements MetricSamplesDao {
  constructor(private readonly pool: pg.Pool) {}

  async insert(input: CreateMetricSampleInput): Promise<MetricSample> {
    const res = await this.pool.query<{ id: number }>(
      `INSERT INTO metric_samples
         (customer_id, service, bucket_ts, window_sec, request_count, error_count,
          error_rate, p50_ms, p95_ms, p99_ms)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
       RETURNING id`,
      [
        input.customer_id,
        input.service,
        input.bucket_ts,
        input.window_sec,
        input.request_count,
        input.error_count,
        input.error_rate,
        input.p50_ms,
        input.p95_ms,
        input.p99_ms,
      ],
    );
    return { ...input, id: Number(res.rows[0]!.id) };
  }

  /** Most recent sample for a service (highest `bucket_ts`). */
  async latestForService(
    customerId: string,
    service: string,
  ): Promise<MetricSample | null> {
    const res = await this.pool.query<MetricSample>(
      `SELECT * FROM metric_samples
        WHERE customer_id = $1 AND service = $2
        ORDER BY bucket_ts DESC LIMIT 1`,
      [customerId, service],
    );
    return res.rows[0] ?? null;
  }

  /** Ascending time series for a service since `sinceTs` (capped by `limit`). */
  async seriesForService(
    customerId: string,
    service: string,
    sinceTs: number,
    limit = 240,
  ): Promise<MetricSample[]> {
    const cap = Math.min(Math.max(limit, 1), 240);
    const res = await this.pool.query<MetricSample>(
      `SELECT * FROM metric_samples
        WHERE customer_id = $1 AND service = $2 AND bucket_ts >= $3
        ORDER BY bucket_ts DESC LIMIT $4`,
      [customerId, service, sinceTs, cap],
    );
    return res.rows.reverse();
  }
}
